"""Static, data-free training definitions shared by the application hosts."""

WAREHOUSE_TRAINING = {
    "inventory-locations-scanning": {
        "title": "Inventory, Locations & Scanning",
        "summary": "Find stock, interpret locations, and use barcode or QR scanning without changing quantities.",
        "permissions": ("inventory.view_inventoryitem",),
        "audience": "Warehouse inventory users",
        "duration": "8 minutes",
        "workspace_path": "/inventory/",
        "workspace_permissions": ("inventory.view_inventoryitem",),
        "scenario": "A fictional specialist needs to locate part RPL-DEMO-104, confirm its bin, and verify the label before material is staged.",
        "objectives": (
            "Search by part number, description, category, or location.",
            "Read building, room, rack, section, and bin consistently.",
            "Use scanner results as a lookup aid—not as permission to change stock.",
        ),
        "steps": (
            ("Find the item", "Open Inventory and search for the fictional part or scan its label. Confirm the part number and description before using the result."),
            ("Read the location", "Follow the location hierarchy from building and room through rack, section, and bin. Do not substitute a nearby bin because the audit trail follows the recorded location."),
            ("Check stock context", "Review on-hand quantity, low-stock state, unit, category, and active status. Quantity adjustments belong to receiving, fulfillment, cycle count, or another approved ledger path."),
            ("Use labels safely", "Open the item detail before printing a barcode or QR label. Verify that the printed identifier resolves to the same item before applying it."),
        ),
        "key_points": (
            "Never create a duplicate item to work around a search or location issue.",
            "Scanning identifies an item; it does not bypass permissions or ledger controls.",
            "Report an incorrect label or bin before moving material.",
        ),
    },
    "receiving": {
        "title": "Receiving",
        "summary": "Receive single or multi-line shipments, preserve source details, and verify the stock ledger.",
        "permissions": ("inventory.receive_stock", "inventory.view_receiving_log"),
        "audience": "Receiving specialists",
        "duration": "10 minutes",
        "workspace_path": "/inventory/receiving/",
        "workspace_permissions": ("inventory.receive_stock",),
        "scenario": "A fictional shipment contains two known parts and one new in-scope item that must be received against a purchase order.",
        "objectives": (
            "Match shipment lines to existing inventory before creating new items.",
            "Capture PO, vendor, shipper, packing slip, and quantity accurately.",
            "Confirm that posting created the expected immutable receipt transactions.",
        ),
        "steps": (
            ("Verify shipment identity", "Compare the physical packing slip, PO, vendor, and shipper before entering quantities. Resolve duplicate or ambiguous part numbers first."),
            ("Build the receiving ticket", "Select each existing item and enter the physically received quantity. Create a new item only when the catalog has no valid match and the material is in scope."),
            ("Post the receipt", "Review every line, then submit once. Posting updates on-hand inventory through the receiving and ledger service; do not compensate by editing the item quantity directly."),
            ("Confirm the audit trail", "Open Receiving History and verify the ticket, operator, source references, line quantities, and resulting inventory transactions."),
        ),
        "key_points": (
            "Receive what physically arrived, not the ordered quantity.",
            "Use a reversal or approved correction path for mistakes.",
            "Attach source documents when they are needed for later reconciliation.",
        ),
    },
    "pick-tickets-qa": {
        "title": "Pick Tickets & QA",
        "summary": "Accept assigned work, record actual quantities, explain variances, and complete independent QA.",
        "permissions": ("inventory.view_pickticket",),
        "audience": "Pickers and QA specialists",
        "duration": "12 minutes",
        "workspace_path": "/tickets/",
        "workspace_permissions": ("inventory.view_pickticket",),
        "scenario": "A fictional ticket requests three lines. Two are filled exactly and one is short by one unit.",
        "objectives": (
            "Acknowledge assignment before fulfillment.",
            "Record the actual quantity for every line.",
            "Keep picker and QA identities separate and auditable.",
        ),
        "steps": (
            ("Accept assigned work", "Open the ticket assigned to you and acknowledge it. Accepted tickets stay locked to that specialist unless a manager performs an audited reassignment."),
            ("Pick by identity and location", "Match the part number and bin location on every line. Do not substitute a similar item or pull from an unrecorded location."),
            ("Record actuals", "Enter the actual picked quantity for every line, including zero. A short or over-pick requires a line-specific variance reason."),
            ("Complete independent QA", "The picker and QA checker must be different authorized users. QA confirms item identity and actual quantity before the ticket advances."),
            ("Finish delivery stages", "Follow the displayed workflow from Picked to Ready for Delivery and Closed/Delivered. Do not skip states or reuse another operator's signoff."),
        ),
        "key_points": (
            "Requested quantity and actual picked quantity are separate facts.",
            "Every variance needs its own reason.",
            "Only managers may reassign an accepted ticket.",
        ),
    },
    "material-request-processing": {
        "title": "Material Request Processing",
        "summary": "Review demand, claim unassigned work, coordinate fulfillment, and preserve requester communication.",
        "permissions": ("inventory.view_materialrequest",),
        "audience": "Warehouse request specialists",
        "duration": "10 minutes",
        "workspace_path": "/material-requests/",
        "workspace_permissions": ("inventory.view_materialrequest",),
        "scenario": "A fictional request arrives with a required delivery slot, three material lines, and one urgent note.",
        "objectives": (
            "Review requester, delivery, urgency, and line details together.",
            "Use first-claim assignment and assignment acknowledgement correctly.",
            "Keep the request and its linked pick ticket synchronized.",
        ),
        "steps": (
            ("Review the request", "Confirm requester identity, delivery location, delivery slot, notes, urgency, and each requested line before accepting work."),
            ("Claim or assign", "An eligible specialist may accept unassigned work. Managers supervise and may reassign, but routine claim alerts are intended for frontline specialists."),
            ("Acknowledge ownership", "The assigned specialist completes assignment acknowledgement before fulfillment. Reassignment resets acknowledgement for the new owner."),
            ("Process the linked ticket", "Use the linked pick ticket for actual quantities and QA. Do not recreate or separately edit fulfillment rows outside the synchronized workflow."),
            ("Close the communication loop", "Advance ready, delivery, and completion states using the available actions so the requester sees the current outcome."),
        ),
        "key_points": (
            "Request ownership and pick-ticket ownership must match.",
            "Do not retry an action blindly after an error; first confirm whether it committed.",
            "Use events and notes for operational communication rather than changing historical facts.",
        ),
    },
    "shortages-procurement": {
        "title": "Shortages, Backorders & Procurement",
        "summary": "Resolve short demand per line without allowing negative inventory, then track sourcing and later fulfillment.",
        "permissions": (
            "inventory.view_materialbackorder",
            "inventory.manage_backorders",
            "inventory.view_procurementrequisition",
            "inventory.manage_procurement_requisitions",
        ),
        "audience": "Warehouse and Procurement specialists",
        "duration": "12 minutes",
        "workspace_path": "/backorders/",
        "workspace_permissions": ("inventory.view_materialbackorder", "inventory.manage_backorders"),
        "scenario": "A fictional request needs ten units, but only six are available. The remaining four must receive an explicit disposition.",
        "objectives": (
            "Allocate no more than available stock.",
            "Choose cancel, backorder, or Procurement for each short line.",
            "Preserve links from original demand through receipt and supplemental fulfillment.",
        ),
        "steps": (
            ("Identify the shortage", "Compare requested demand with the available allocation shown by the system. Inventory must never become negative."),
            ("Choose a line disposition", "For the unallocated quantity, choose whether to cancel it, request it when available, or ask Procurement to purchase it."),
            ("Manage the backorder", "Track remaining demand and status from the Backorders workspace. Do not create an unrelated request to replace the linked shortage."),
            ("Work the Procurement requisition", "Review the linked demand, sourcing status, expected quantity, and notes. Keep the requisition tied to its backorder."),
            ("Fulfill later stock", "When stock arrives, use the supplemental fulfillment path so the receipt, backorder reduction, pick ticket, and requester outcome remain linked."),
        ),
        "key_points": (
            "Every short line requires an explicit decision.",
            "Generic deletion is blocked after operational processing.",
            "Use linked receiving and fulfillment records for complete auditability.",
        ),
    },
    "cycle-counts": {
        "title": "Cycle Counts",
        "summary": "Create, perform, review, and archive controlled counts without bypassing stock reconciliation.",
        "permissions": ("inventory.perform_cycle_count", "inventory.manage_cycle_counts"),
        "audience": "Inventory control specialists",
        "duration": "9 minutes",
        "workspace_path": "/cycle-counts/",
        "workspace_permissions": ("inventory.perform_cycle_count", "inventory.manage_cycle_counts"),
        "scenario": "A fictional count covers one rack with six items, including a quantity discrepancy that needs review.",
        "objectives": (
            "Understand the count scope and assignment before starting.",
            "Enter a blind count from the physical location.",
            "Review and reconcile discrepancies through the controlled workflow.",
        ),
        "steps": (
            ("Prepare the count", "Confirm the selected location or item scope, assigned counter, and active status. Avoid receiving or picking the same stock while the count is underway."),
            ("Perform the blind count", "Count the physical units without copying the expected quantity. Enter zero when no stock is present rather than leaving the field ambiguous."),
            ("Review discrepancies", "Compare counted and expected quantities after submission. Recount surprising differences before approval."),
            ("Reconcile and archive", "Use the authorized reconciliation step to create the stock adjustment and ledger evidence, then archive the completed count when permitted."),
        ),
        "key_points": (
            "A cycle count is not a direct item edit.",
            "Physical evidence comes before reconciliation.",
            "Archived counts remain part of inventory history.",
        ),
    },
    "transactions-reports": {
        "title": "Transactions, Audit & Reports",
        "summary": "Trace quantity changes and use operational reports without rewriting history.",
        "permissions": ("inventory.view_inventorytransaction",),
        "audience": "Warehouse auditors and managers",
        "duration": "8 minutes",
        "workspace_path": "/transactions/",
        "workspace_permissions": ("inventory.view_inventorytransaction",),
        "scenario": "A fictional manager investigates why an item changed from 20 units to 14 after receiving, reservation, and variance events.",
        "objectives": (
            "Read transaction signs, types, operators, and source references.",
            "Connect reports back to underlying operational records.",
            "Distinguish correction workflows from historical edits.",
        ),
        "steps": (
            ("Filter the ledger", "Search the immutable transaction history by item, type, date, operator, or source context. Read positive and negative signs numerically."),
            ("Follow source links", "Open the receiving, request, ticket, count, or correction record that caused the movement. A report summary is not the source of truth by itself."),
            ("Review operational reports", "Use the permitted report period and category filters, then compare totals with source records when something is unexpected."),
            ("Correct through workflow", "Never rewrite an old ledger row. Use reversal, fulfillment reconciliation, cycle count, or another approved process so the correction is itself audited."),
        ),
        "key_points": (
            "The immutable transaction history explains every quantity change.",
            "Exports inherit the same permission and data-handling responsibilities as the screen.",
            "Unexpected numbers require source review, not direct database correction.",
        ),
    },
    "users-permissions": {
        "title": "Users & Permissions",
        "summary": "Provision, review, reset, deactivate, and remove access without crossing application boundaries.",
        "permissions": ("inventory.manage_users", "inventory.manage_groups", "inventory.manage_group_permissions"),
        "audience": "Authorized access managers",
        "duration": "10 minutes",
        "workspace_path": "/settings/users/",
        "workspace_permissions": ("inventory.manage_users",),
        "scenario": "A fictional employee changes roles and needs requester access retained while Warehouse and Equipment Manager access are removed.",
        "objectives": (
            "Apply least-privilege access through managed groups and permissions.",
            "Keep requester and manager application boundaries separate.",
            "Preserve operator attribution when removing access.",
        ),
        "steps": (
            ("Confirm the requested role", "Verify the user's business responsibility and which application hosts they need. Do not treat all RPL applications as one shared permission."),
            ("Grant least-privilege access", "Assign only the managed groups and permissions needed for the role. Equipment requester access never grants Equipment Manager access."),
            ("Review sensitive capabilities", "Check user administration, imports, audit history, costs, receiving, fulfillment, Procurement, and manager overrides separately."),
            ("Reset or remove access safely", "Use the managed reset or removal workflow. Never change a production password for testing, and retain historical identities when operational records reference them."),
            ("Verify boundaries", "Confirm the user can reach the intended host and receives a denial on manager or cross-resource routes they do not own."),
        ),
        "key_points": (
            "Permissions—not visible navigation—enforce access.",
            "Requester-only accounts must remain outside manager applications.",
            "Deactivation is often safer than deletion when audit history exists.",
        ),
    },
}


EQUIPMENT_TRAINING = {
    "asset-register": {
        "title": "Equipment Asset Register",
        "summary": "Create and maintain serialized equipment identity, lifecycle status, location, and labels.",
        "permissions": ("equipment.view_asset",),
        "audience": "Equipment specialists",
        "duration": "9 minutes",
        "workspace_path": "/assets/",
        "workspace_permissions": ("equipment.view_asset",),
        "scenario": "A fictional technician registers a new serialized device, verifies its tag, and prepares its label before issue.",
        "objectives": (
            "Maintain one authoritative asset identity.",
            "Separate descriptive edits from custody and lifecycle transitions.",
            "Use barcode and QR labels without exposing sensitive fields.",
        ),
        "steps": (
            ("Search before creating", "Search asset tag, serial number, name, and category to prevent duplicates. Placeholder or ambiguous identifiers are not valid unique identity."),
            ("Create the asset identity", "Record the authoritative asset tag, serial, category, condition, location, and other permitted fields. Costs remain permission-controlled."),
            ("Review lifecycle state", "Use the asset detail to understand availability, holds, custody, maintenance, and archive state. Do not overwrite current custody with a generic edit."),
            ("Print and verify the label", "Generate the asset label, scan it, and confirm it resolves uniquely to the same record before attaching it."),
        ),
        "key_points": (
            "Serialized equipment is not quantity-based inventory.",
            "Custody and lifecycle changes use dedicated audited services.",
            "Ambiguous scans must fail closed.",
        ),
    },
    "custody-returns": {
        "title": "Equipment Custody & Returns",
        "summary": "Issue assets, document transfer, receive returns, and preserve complete custody history.",
        "permissions": ("equipment.view_checkout",),
        "audience": "Equipment custody specialists",
        "duration": "11 minutes",
        "workspace_path": "/checkouts/",
        "workspace_permissions": ("equipment.view_checkout",),
        "scenario": "A fictional laptop is issued to a team, transferred to a named custodian, and returned with a condition note.",
        "objectives": (
            "Create custody from an available or properly allocated asset.",
            "Record destination, custodian, dates, and condition accurately.",
            "Preserve historical custody when the current assignment changes.",
        ),
        "steps": (
            ("Confirm availability", "Open the asset and check current status, reservation holds, maintenance state, and active custody before issue."),
            ("Create the checkout", "Select the authorized requestor or team, destination, expected return, and included assets. Review the complete issue before submitting."),
            ("Document the handoff", "Use the checkout record as the operational source. Do not edit the asset's current party directly to simulate custody."),
            ("Process the return", "Record return date, condition, location, meter information when relevant, and any follow-up maintenance need."),
            ("Review custody history", "Verify the closed checkout and immutable events remain visible after the asset becomes available or moves to its next state."),
        ),
        "key_points": (
            "Past, current, and approved future custody are separate auditable facts.",
            "A return never erases the prior custodian.",
            "Reservation holds must be resolved before conflicting custody actions.",
        ),
    },
    "reservations": {
        "title": "Equipment Reservations",
        "summary": "Approve future need, hold assets, avoid conflicts, and convert reservations into real custody.",
        "permissions": ("equipment.view_reservation", "equipment.manage_reservations"),
        "audience": "Equipment reservation coordinators",
        "duration": "9 minutes",
        "workspace_path": "/reservations/",
        "workspace_permissions": ("equipment.view_reservation",),
        "scenario": "A fictional project reserves two devices for next week, then converts the approved hold into a checkout.",
        "objectives": (
            "Check current and overlapping future availability.",
            "Create approved future custody without changing current custody.",
            "Release or fulfill holds through explicit transitions.",
        ),
        "steps": (
            ("Review the requested window", "Confirm requestor, destination, start, expected return, and the exact assets or category need."),
            ("Check conflicts", "Review active custody, maintenance, terminal states, and overlapping approved reservations before approval."),
            ("Approve the hold", "Approval creates an enforceable hold for approved future custody. It must not overwrite a current custodian."),
            ("Fulfill or cancel", "Fulfillment creates a linked checkout and custody history. Cancellation releases the hold and records why the plan changed."),
        ),
        "key_points": (
            "Approved reservations must block conflicting allocation.",
            "Fulfilled means real custody was created—not merely a status label.",
            "Maintenance cannot silently destroy an active hold.",
        ),
    },
    "maintenance-rentals": {
        "title": "Equipment Maintenance & Rentals",
        "summary": "Control service work, recurring plans, meter readings, rentals, and return obligations.",
        "permissions": (
            "equipment.view_maintenanceworkorder",
            "equipment.manage_maintenance",
            "equipment.view_rentalcontract",
            "equipment.manage_rentals",
        ),
        "audience": "Equipment operations specialists",
        "duration": "12 minutes",
        "workspace_path": "/maintenance/",
        "workspace_permissions": ("equipment.view_maintenanceworkorder",),
        "scenario": "A fictional vehicle reaches its service interval while a rented device approaches its expected return date.",
        "objectives": (
            "Generate and complete auditable maintenance work.",
            "Keep recurring schedules and meter evidence current.",
            "Monitor open rental lines and return obligations.",
        ),
        "steps": (
            ("Review service and rental obligations", "Use the attention queues to identify due work orders, recurring plans, meter thresholds, rental deadlines, and overdue returns."),
            ("Prepare maintenance", "Confirm the asset has no conflicting approved reservation or active custody that makes service unsafe. Record plan, priority, due date, and scope."),
            ("Record progress and completion", "Advance the work order through supported states and capture completion details, meter reading, service notes, and permitted cost fields."),
            ("Manage rental returns", "Track each open rental line using its expected return date with contract-end fallback. Record return without erasing the contract or obligation history."),
            ("Confirm final asset state", "Terminal-state assets must not become Available merely because maintenance completed. Review lifecycle and location after every transition."),
        ),
        "key_points": (
            "Recurring generation must not create duplicate work orders.",
            "Costs are visible only with the dedicated permission.",
            "Service completion preserves the asset's valid lifecycle state.",
        ),
    },
    "request-queue": {
        "title": "Equipment Request Queue",
        "summary": "Review requester demand, allocate serialized assets, and move requests through fulfillment safely.",
        "permissions": ("equipment.manage_equipment_requests",),
        "audience": "Equipment request managers",
        "duration": "11 minutes",
        "workspace_path": "/requests/",
        "workspace_permissions": ("equipment.manage_equipment_requests",),
        "scenario": "A fictional requester asks for two devices, prefers one named asset, and needs delivery to a project location.",
        "objectives": (
            "Keep requester identity and manager authority separate.",
            "Review category needs and preferred items without promising unavailable assets.",
            "Allocate specific assets and preserve request-to-custody audit links.",
        ),
        "steps": (
            ("Triage the request", "Review purpose, destination, dates, requester notes, categories, quantities, and any preferred serialized item."),
            ("Assign a manager", "Use the queue assignment action so responsibility is visible and audited."),
            ("Allocate specific assets", "Revalidate category, availability, holds, archive state, and duplicate allocation under the controlled service before committing."),
            ("Advance the request", "Move through Review, Approved, Ready, and Fulfilled only when the operational evidence supports each state."),
            ("Create fulfillment records", "Approved reservations, checkouts, custody, and events remain the authoritative operational history after the request is fulfilled."),
        ),
        "key_points": (
            "Requester accounts never receive Equipment Manager access.",
            "A preferred item is a request—not an allocation guarantee.",
            "Permanent deletion is manager-only and preserves an immutable tombstone.",
        ),
    },
    "imports-reporting": {
        "title": "Equipment Imports & Reporting",
        "summary": "Stage heterogeneous workbooks, review exceptions, approve safe rows, and use permission-filtered reports.",
        "permissions": ("equipment.import_equipment", "equipment.export_equipment", "equipment.view_equipment_audit"),
        "audience": "Equipment data stewards and auditors",
        "duration": "12 minutes",
        "workspace_path": "/imports/",
        "workspace_permissions": ("equipment.import_equipment",),
        "scenario": "A fictional workbook contains clean assets, a duplicate serial, a component row, and one pre-assigned asset requiring custody history.",
        "objectives": (
            "Treat import as staged review rather than direct spreadsheet mutation.",
            "Resolve ambiguous identity and lifecycle rows before approval.",
            "Keep report, audit, export, and cost permissions independent.",
        ),
        "steps": (
            ("Upload to staged import", "Choose the workbook and create a staged import batch. The upload does not make spreadsheet rows authoritative assets by itself."),
            ("Review normalized rows", "Check source sheet and row, proposed identity, category, status, location, custody, components, formulas, and validation messages."),
            ("Resolve exceptions", "Reject placeholders, duplicates, ambiguous scanner values, unsafe formulas, and incomplete custody. Correct the source or approved staging fields explicitly."),
            ("Approve the staged import", "Apply only reviewed rows through the serialized equipment mutation service. Pre-assigned assets require baseline checkout and immutable provenance."),
            ("Validate reports and exports", "Use reports and audit history to confirm imported state. Exports omit costs and sensitive fields unless the user has the dedicated permissions."),
        ),
        "key_points": (
            "A staged import preserves raw source provenance.",
            "Blank or format-only rows must never create assets.",
            "CSV output must neutralize spreadsheet formulas.",
        ),
    },
}
