from django.urls import path

from . import views
from . import onboarding_views

urlpatterns = [
    path("settings/portal-access/", onboarding_views.portal_access_queue, name="portal_access_queue"),
    path("settings/portal-access/<int:pk>/", onboarding_views.portal_access_detail, name="portal_access_detail"),
    path("material-requests/email-response/", views.material_request_email_delivery_response, name="material_request_email_delivery_response"),
    path('manifest.webmanifest', views.pwa_manifest, name='pwa_manifest'),
    path('service-worker.js', views.pwa_service_worker, name='pwa_service_worker'),
    path('offline/', views.pwa_offline, name='pwa_offline'),
    path('api/push/config/', views.push_config, name='push_config'),
    path('api/push/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('api/push/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path(
        "material-requests/<int:pk>/confirm-ready/",
        views.material_request_confirm_ready,
        name="material_request_confirm_ready",
    ),
    path("", views.dashboard, name="dashboard"),
    path("search/", views.global_search, name="global_search"),
    path("recently-viewed/", views.recently_viewed, name="recently_viewed"),
    path("inventory/", views.inventory_list, name="inventory_list"),
    path("inventory/new/", views.inventory_edit, name="inventory_new"),
    path("inventory/<int:pk>/edit/", views.inventory_edit, name="inventory_edit"),
    path("inventory/<int:pk>/receive/", views.receive_stock, name="receive_stock"),
    path("inventory/<int:pk>/labels/", views.inventory_labels, name="inventory_labels"),
    path("inventory/<int:pk>/barcode/", views.item_barcode_print, name="item_barcode_print"),
    path("inventory/<int:pk>/assign-upc/", views.item_upc_assign, name="item_upc_assign"),
    path("inventory/<int:pk>/", views.item_detail, name="item_detail"),
    path("inventory/<int:pk>/history/", views.item_transaction_history, name="item_transaction_history"),
    path("inventory/low-stock/", views.low_stock_list, name="low_stock_list"),
    path("inventory/import.xlsx", views.inventory_import_xlsx, name="inventory_import_xlsx"),
    path("inventory/clear/", views.inventory_clear, name="inventory_clear"),
    path("inventory/<int:pk>/delete/", views.inventory_delete, name="inventory_delete"),
    path("inventory/export.csv", views.export_inventory_csv, name="export_inventory_csv"),
    path("inventory/export.xlsx", views.export_inventory_xlsx, name="export_inventory_xlsx"),
    path("inventory/export/", views.export_center, name="export_center"),
    path("inventory/receiving/", views.receiving, name="receiving"),
    path("inventory/receiving-log/", views.receiving_log, name="receiving_log"),
    path("receiving-tickets/<int:pk>/print/", views.receiving_ticket_print, name="receiving_ticket_print"),
    path("receiving-tickets/<int:pk>/edit/", views.receiving_ticket_edit, name="receiving_ticket_edit"),
    path("receiving-tickets/<int:pk>/delete/", views.receiving_ticket_delete, name="receiving_ticket_delete"),
    # Batch adjustment is intentionally separate from selection-based bulk edit.
    path("inventory/batch-adjust/", views.bulk_adjust, name="batch_adjust"),
    path("inventory/bulk-edit/", views.inventory_bulk_edit, name="inventory_bulk_edit"),
    # Compatibility name retained for existing bookmarks and integrations.
    path("inventory/bulk-edit/", views.inventory_bulk_edit, name="bulk_adjust"),
    path("qr-codes/", views.qr_codes, name="qr_codes"),
    path("qr-codes/app/", views.app_qr_code, name="app_qr_code"),
    path("tickets/", views.ticket_list, name="ticket_list"),
    path("tickets/new/", views.ticket_create, name="ticket_create"),
    path("tickets/export.csv", views.export_tickets_csv, name="export_tickets_csv"),
    path("tickets/<int:pk>/", views.ticket_detail, name="ticket_detail"),
    path("tickets/<int:pk>/edit/", views.ticket_edit, name="ticket_edit"),
    path("tickets/<int:pk>/status/", views.ticket_status_update, name="ticket_status_update"),
    path("tickets/<int:pk>/print/", views.ticket_print, name="ticket_print"),
    path("tickets/<int:pk>/print/pdf/", views.ticket_print_pdf, name="ticket_print_pdf"),
    path("tickets/<int:pk>/delete/", views.ticket_delete, name="ticket_delete"),
    path("scanner/", views.scanner, name="scanner"),
    path("scan-lookup/", views.scan_lookup, name="scan_lookup"),
    path("scan-lookup-api/", views.scan_lookup_api, name="scan_lookup_api"),
    path("item-search-api/", views.item_search_api, name="item_search_api"),
    path("transactions/", views.transaction_history, name="transaction_history"),
    path("transactions/export.csv", views.export_transactions_csv, name="export_transactions_csv"),
    # Location-based QR views
    path("locations/", views.location_list, name="location_list"),
    path("locations/print/", views.location_qr_print, name="location_qr_print"),
    path("locations/<str:location_key>/", views.location_detail, name="location_detail"),
    path("locations/<str:location_key>/add/", views.location_add_item, name="location_add_item"),
    path("locations/<str:location_key>/remove/<int:item_pk>/", views.location_remove_item, name="location_remove_item"),
    path("settings/", views.settings, name="settings"),
    path("settings/users/", views.user_management, name="user_management"),
    path("settings/users/add/", views.user_create, name="user_create"),
    path("settings/users/<int:pk>/edit/", views.user_edit, name="user_edit"),
    path("settings/users/<int:pk>/delete/", views.user_delete, name="user_delete"),
    path("settings/users/<int:pk>/unlock/", views.user_unlock, name="user_unlock"),
    path("settings/groups/", views.group_management, name="group_management"),
    path("settings/groups/add/", views.group_create, name="group_create"),
    path("settings/groups/<int:pk>/permissions/", views.group_permissions, name="group_permissions"),
    path("settings/groups/<int:pk>/rename/", views.group_rename, name="group_rename"),
    path("settings/groups/<int:pk>/delete/", views.group_delete, name="group_delete"),
    path("settings/groups/<str:group_name>/update/", views.group_update, name="group_update"),
    path("settings/password/", views.change_password, name="change_password"),
    # Item Images and Documents
    path("inventory/<int:item_id>/images/", views.item_images, name="item_images"),
    path("inventory/<int:item_id>/images/add/", views.item_image_add, name="item_image_add"),
    path("inventory/<int:item_id>/images/<int:image_id>/delete/", views.item_image_delete, name="item_image_delete"),
    path(
        "inventory/<int:item_id>/images/<int:image_id>/file/",
        views.serve_item_image,
        name="serve_item_image",
    ),
    path("inventory/<int:item_id>/documents/", views.item_documents, name="item_documents"),
    path("inventory/<int:item_id>/documents/add/", views.item_document_add, name="item_document_add"),
    path("inventory/<int:item_id>/documents/<int:doc_id>/delete/", views.item_document_delete, name="item_document_delete"),
    path(
        "inventory/<int:item_id>/documents/<int:doc_id>/file/",
        views.serve_item_document,
        name="serve_item_document",
    ),
    path("material-requests/", views.material_request_board, name="material_request_board"),
    path("material-requests/archive/", views.material_request_archive, name="material_request_archive"),
    path("material-requests/new/", views.material_request_create, name="material_request_create"),
    path("material-requests/<int:pk>/", views.material_request_detail, name="material_request_detail"),
    path(
        "material-requests/<int:pk>/delivery-response/",
        views.material_request_delivery_response,
        name="material_request_delivery_response",
    ),
    path("material-requests/<int:pk>/edit/", views.material_request_edit, name="material_request_edit"),
    path("material-requests/<int:pk>/delete/", views.material_request_delete, name="material_request_delete"),
    path("material-requests/<int:pk>/assign/", views.material_request_assign, name="material_request_assign"),
    path("api/material-request-events/", views.material_request_events, name="material_request_events"),
    # Cycle counting
    path("cycle-counts/", views.cycle_count_list, name="cycle_count_list"),
    path("cycle-counts/archive/", views.cycle_count_archive, name="cycle_count_archive"),
    path("cycle-counts/new/", views.cycle_count_create, name="cycle_count_create"),
    path("cycle-counts/<int:pk>/", views.cycle_count_detail, name="cycle_count_detail"),
    path("cycle-counts/<int:pk>/pdf/", views.cycle_count_pdf, name="cycle_count_pdf"),
    path("cycle-counts/<int:pk>/results-pdf/", views.cycle_count_results_pdf, name="cycle_count_results_pdf"),
    path("cycle-counts/<int:pk>/archive/", views.cycle_count_archive_action, name="cycle_count_archive_action"),
    path("cycle-counts/<int:pk>/unarchive/", views.cycle_count_unarchive_action, name="cycle_count_unarchive_action"),
    # Manager reports
    path("reports/", views.reports_index, name="reports_index"),
    path("reports/daily/", views.reports_daily, name="reports_daily"),
    path("reports/<str:kind>/pdf/", views.reports_pdf, name="reports_pdf"),
    path("reports/<str:kind>/viewer/", views.reports_pdf_viewer, name="reports_pdf_viewer"),
]
