# Generated by Django 6.1.1 on 2026-09-16 02:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=64, unique=True)),
                ('legacy_tag', models.CharField(blank=True, max_length=120)),
                ('source_namespace', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=220)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('ownership', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('LEASED', 'Leased'), ('CUSTOMER', 'Customer owned'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CHECKED_OUT', 'Checked out'), ('IN_TRANSIT', 'In transit'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out of service'), ('LOST', 'Lost'), ('RETIRED', 'Retired'), ('RETURNED_VENDOR', 'Returned to vendor'), ('UNKNOWN', 'Unknown')], default='AVAILABLE', max_length=24)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('review_required', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_equipment_assets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_assets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_equipment_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('asset_tag',),
                'permissions': [('access_equipment_portal', 'Can access equipment portal'), ('manage_equipment', 'Can manage equipment registry'), ('checkout_asset', 'Can check out equipment'), ('return_asset', 'Can return equipment'), ('manage_reservations', 'Can manage equipment reservations'), ('manage_maintenance', 'Can manage equipment maintenance'), ('manage_rentals', 'Can manage equipment rentals'), ('import_equipment', 'Can import equipment'), ('export_equipment', 'Can export equipment'), ('view_asset_costs', 'Can view equipment costs'), ('view_equipment_audit', 'Can view equipment audit history'), ('print_asset_labels', 'Can print equipment labels')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('requires_serial', models.BooleanField(default=False)),
                ('default_checkout_days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'equipment categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('room', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('vendor_code', models.CharField(blank=True, max_length=60)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='equipment/documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(choices=[('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=16)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='equipment.asset')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_number', models.CharField(max_length=24, unique=True)),
                ('borrower_snapshot', models.CharField(max_length=240)),
                ('purpose', models.TextField(blank=True)),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_checkouts', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentlocation')),
            ],
            options={
                'ordering': ('-checked_out_at',),
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag_snapshot', models.CharField(max_length=64)),
                ('asset_name_snapshot', models.CharField(max_length=220)),
                ('condition_out', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_items', to='equipment.asset')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='equipment.checkout')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='equipment.equipmentcategory'),
        ),
        migrations.CreateModel(
            name='EquipmentImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('accepted_rows', models.PositiveIntegerField(default=0)),
                ('review_rows', models.PositiveIntegerField(default=0)),
                ('excluded_rows', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(max_length=120)),
                ('row_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REVIEW', 'Needs review'), ('EXCLUDED', 'Excluded'), ('ARTIFACT', 'Artifact/template'), ('ERROR', 'Error')], max_length=16)),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('messages', models.JSONField(default=list)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='equipment.asset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='equipment.equipmentimportbatch')),
            ],
            options={
                'ordering': ('sheet_name', 'row_number'),
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_assets', to='equipment.equipmentlocation'),
        ),
        migrations.AddField(
            model_name='asset',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_assets', to='equipment.equipmentlocation'),
        ),
        migrations.CreateModel(
            name='EquipmentParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('PERSON', 'Person'), ('TEAM', 'Team'), ('DEPARTMENT', 'Department'), ('PROJECT', 'Project'), ('EXTERNAL', 'External')], default='PERSON', max_length=16)),
                ('display_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_party', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'equipment parties',
                'ordering': ('display_name',),
            },
        ),
        migrations.AddField(
            model_name='checkout',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='equipment.equipmentparty'),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assets', to='equipment.equipmentparty'),
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order_number', models.CharField(max_length=24, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('problem_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('WAITING_PARTS', 'Waiting for parts'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=12)),
                ('out_of_service', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('work_performed', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='equipment.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_equipment_work', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_equipment_work', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentvendor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=80, unique=True)),
                ('po_number', models.CharField(blank=True, max_length=80)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='equipment.equipmentvendor')),
            ],
            options={
                'ordering': ('-starts_on', 'contract_number'),
            },
        ),
        migrations.CreateModel(
            name='RentalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_equipment_number', models.CharField(blank=True, max_length=120)),
                ('rate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_period', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('FOUR_WEEK', 'Four weeks'), ('MONTH', 'Month')], default='FOUR_WEEK', max_length=16)),
                ('expected_return_on', models.DateField(blank=True, null=True)),
                ('returned_on', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_lines', to='equipment.asset')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='equipment.rentalcontract')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(max_length=24, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('purpose', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_equipment_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_reservations', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentlocation')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='equipment.equipmentparty')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.AddField(
            model_name='checkout',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.reservation'),
        ),
        migrations.CreateModel(
            name='ReservationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.asset')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='assets',
            field=models.ManyToManyField(related_name='reservations', through='equipment.ReservationAsset', to='equipment.asset'),
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition_in', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged'), ('UNSERVICEABLE', 'Unserviceable'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('damage_reported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='return_record', to='equipment.checkoutitem')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('return_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveCustody',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='active_custody', serialize=False, to='equipment.asset')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipmentparty')),
                ('checkout_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='active_custody', to='equipment.checkoutitem')),
            ],
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=220)),
                ('model_number', models.CharField(blank=True, max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='equipment.asset')),
            ],
            options={
                'ordering': ('asset', 'role', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='equipment_component_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IMPORTED', 'Imported'), ('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CHECKED_OUT', 'Checked out'), ('RETURNED', 'Returned'), ('RESERVED', 'Reserved'), ('RESERVATION_CHANGED', 'Reservation changed'), ('MAINTENANCE_OPENED', 'Maintenance opened'), ('MAINTENANCE_COMPLETED', 'Maintenance completed'), ('STATUS_CHANGED', 'Status changed'), ('REVIEWED', 'Reviewed')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='equipment.asset')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['asset', 'occurred_at'], name='equipment_a_asset_i_927258_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SERIAL', 'Serial number'), ('BASE_SERIAL', 'Base serial'), ('VIN', 'VIN'), ('LICENSE_PLATE', 'License plate'), ('IMEI', 'IMEI'), ('GPS_SERIAL', 'GPS serial'), ('EQUIPMENT_NUMBER', 'Equipment number'), ('BARCODE', 'Barcode'), ('TRACKING', 'Tracking'), ('OTHER', 'Other')], max_length=32)),
                ('namespace', models.CharField(default='global', max_length=120)),
                ('value', models.CharField(max_length=220)),
                ('normalized_value', models.CharField(editable=False, max_length=220)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='equipment.asset')),
            ],
            options={
                'ordering': ('kind', 'value'),
                'constraints': [models.UniqueConstraint(fields=('namespace', 'kind', 'normalized_value'), name='equipment_identifier_unique'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('asset', 'kind'), name='equipment_one_primary_identifier')],
            },
        ),
        migrations.AddConstraint(
            model_name='checkoutitem',
            constraint=models.UniqueConstraint(fields=('checkout', 'asset'), name='equipment_checkout_asset_unique'),
        ),
        migrations.AddConstraint(
            model_name='equipmentimportrow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet_name', 'row_number'), name='equipment_import_row_unique'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='equipment_a_status_35e039_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['source_namespace', 'legacy_tag'], name='equipment_a_source__278992_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['updated_at'], name='equipment_a_updated_c29bad_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='equipment_asset_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('archived_by__isnull', True)), models.Q(('archived_at__isnull', False), ('archived_by__isnull', False)), _connector='OR'), name='equipment_asset_archive_pair'),
        ),
        migrations.AddConstraint(
            model_name='rentalasset',
            constraint=models.UniqueConstraint(fields=('contract', 'asset'), name='equipment_rental_asset_unique'),
        ),
        migrations.AddConstraint(
            model_name='reservationasset',
            constraint=models.UniqueConstraint(fields=('reservation', 'asset'), name='equipment_reservation_asset_unique'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='equipment_reservation_dates'),
        ),
    ]
