# Generated by Django 6.1.1 on 2026-09-16 02:51

from django.db import migrations, models


def seed_lock(apps, schema_editor):
    EquipmentMutationLock = apps.get_model("equipment", "EquipmentMutationLock")
    EquipmentMutationLock.objects.get_or_create(key="global")


def remove_lock(apps, schema_editor):
    EquipmentMutationLock = apps.get_model("equipment", "EquipmentMutationLock")
    EquipmentMutationLock.objects.filter(key="global").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMutationLock',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('touched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipment mutation lock',
            },
        ),
        migrations.RunPython(seed_lock, remove_lock),
    ]
