# Generated by Django 6.1.1 on 2026-09-18 01:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_mutation_lock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(editable=False, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWING', 'Under review'), ('APPROVED', 'Approved'), ('READY', 'Ready'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=12)),
                ('needed_from', models.DateField()),
                ('needed_until', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(max_length=220)),
                ('purpose', models.TextField()),
                ('project', models.CharField(blank=True, max_length=180)),
                ('accepts_substitutes', models.BooleanField(default=True)),
                ('requester_notes', models.TextField(blank=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_equipment_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_equipment_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests', to=settings.AUTH_USER_MODEL)),
                ('requestor_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_requests', to='equipment.equipmentparty')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_request', to='equipment.reservation')),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': [('access_equipment_requests', 'Can access equipment requests portal'), ('manage_equipment_requests', 'Can manage equipment requests')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('CANCELLED', 'Cancelled'), ('ASSIGNED', 'Assigned'), ('ALLOCATED', 'Allocated'), ('STATUS_CHANGED', 'Status changed')], max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='equipment.equipmentrequest')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlisted_equipment', models.CharField(blank=True, max_length=220)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='equipment.equipmentcategory')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='equipment.equipmentrequest')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_allocations', to='equipment.asset')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='equipment.equipmentrequestline')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='equipmentrequest',
            index=models.Index(fields=['status', 'needed_from'], name='equipment_e_status_6ddb57_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentrequest',
            index=models.Index(fields=['requester', 'created_at'], name='equipment_e_request_b44bae_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('needed_until__isnull', True), ('needed_until__gte', models.F('needed_from')), _connector='OR'), name='equipment_request_needed_dates'),
        ),
        migrations.AddIndex(
            model_name='equipmentrequestevent',
            index=models.Index(fields=['request', 'occurred_at'], name='equipment_e_request_2588b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='equipment_request_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('category__isnull', False), models.Q(('unlisted_equipment', ''), _negated=True), _connector='OR'), name='equipment_request_line_has_equipment'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequestallocation',
            constraint=models.UniqueConstraint(fields=('line', 'asset'), name='equipment_request_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequestallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='equipment_request_allocation_quantity_positive'),
        ),
    ]
