# Generated by Django 6.1.1 on 2026-09-18 01:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentrequest_equipmentrequestevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='meter_at_completion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='meter_due',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='occurrence_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('calendar_interval_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meter_type', models.CharField(blank=True, choices=[('ODOMETER', 'Odometer'), ('ENGINE_HOURS', 'Engine hours')], max_length=16)),
                ('meter_interval', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('lead_days', models.PositiveSmallIntegerField(default=14)),
                ('lead_meter', models.DecimalField(decimal_places=1, default=0, max_digits=14)),
                ('default_priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('auto_create_work_order', models.BooleanField(default=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_meter', models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True)),
                ('next_due_date', models.DateField(blank=True, editable=False, null=True)),
                ('next_due_meter', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=14, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='equipment.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_plans', to=settings.AUTH_USER_MODEL)),
                ('preferred_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='equipment.equipmentvendor')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_maintenance_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('asset__asset_tag', 'service_title'),
            },
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.maintenanceplan'),
        ),
        migrations.CreateModel(
            name='VehicleMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('ODOMETER', 'Odometer'), ('ENGINE_HOURS', 'Engine hours')], max_length=16)),
                ('value', models.DecimalField(decimal_places=1, max_digits=14)),
                ('reading_on', models.DateField(default=django.utils.timezone.localdate)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='equipment.asset')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_meter_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reading_on', '-recorded_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('calendar_interval_months__isnull', False), ('meter_interval__isnull', False), _connector='OR'), name='equipment_plan_has_trigger'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('calendar_interval_months__isnull', True), ('calendar_interval_months__gt', 0), _connector='OR'), name='equipment_plan_calendar_positive'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('meter_interval__isnull', True), ('meter_interval__gt', 0), _connector='OR'), name='equipment_plan_meter_positive'),
        ),
        migrations.AddIndex(
            model_name='vehiclemeterreading',
            index=models.Index(fields=['asset', 'meter_type', '-reading_on'], name='equipment_v_asset_i_44e57b_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemeterreading',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='equipment_meter_reading_nonnegative'),
        ),
    ]
