# Generated by Django 6.1.1 on 2026-09-18 01:25

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def preflight_nonnegative_meter_data(apps, schema_editor):
    """Fail before SQLite table rebuilds if legacy rows violate new checks.

    Migration 0005 intentionally remains unchanged. Inspection with
    ``sqlmigrate equipment 0005`` confirms SQLite rebuilds the work-order
    table to add the nullable unique occurrence key. The release procedure
    documents the required backup/maintenance window; this preflight makes
    the additional 0006 constraint rebuild fail clearly before it starts.
    """
    Plan = apps.get_model('equipment', 'MaintenancePlan')
    WorkOrder = apps.get_model('equipment', 'MaintenanceWorkOrder')
    invalid = []
    for field in ('lead_meter', 'last_service_meter', 'next_due_meter'):
        if Plan.objects.filter(**{f'{field}__lt': 0}).exists():
            invalid.append(f'equipment.MaintenancePlan.{field}')
    for field in ('meter_due', 'meter_at_completion'):
        if WorkOrder.objects.filter(**{f'{field}__lt': 0}).exists():
            invalid.append(f'equipment.MaintenanceWorkOrder.{field}')
    if invalid:
        raise RuntimeError(
            'Cannot apply maintenance meter constraints; repair negative values in: '
            + ', '.join(invalid)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_maintenanceworkorder_meter_at_completion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight_nonnegative_meter_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='last_service_meter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='lead_meter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='next_due_meter',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='meter_at_completion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='meter_due',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiclemeterreading',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('lead_meter__gte', 0)), name='equipment_plan_lead_meter_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('last_service_meter__isnull', True), ('last_service_meter__gte', 0), _connector='OR'), name='equipment_plan_last_meter_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.CheckConstraint(condition=models.Q(('next_due_meter__isnull', True), ('next_due_meter__gte', 0), _connector='OR'), name='equipment_plan_next_meter_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkorder',
            constraint=models.CheckConstraint(condition=models.Q(('meter_due__isnull', True), ('meter_due__gte', 0), _connector='OR'), name='equipment_work_meter_due_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceworkorder',
            constraint=models.CheckConstraint(condition=models.Q(('meter_at_completion__isnull', True), ('meter_at_completion__gte', 0), _connector='OR'), name='equipment_work_meter_done_nonnegative'),
        ),
    ]
