# Generated by Django 6.1.1 on 2026-09-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_request_role_cleanup'),
        ('equipment', '0006_maintenance_safety_constraints'),
    ]

    operations = [
    ]
