# Generated by Django 6.1.1 on 2026-09-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_merge_20260918_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequestline',
            name='requested_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_request_lines', to='equipment.asset'),
        ),
        migrations.AddConstraint(
            model_name='equipmentrequestline',
            constraint=models.UniqueConstraint(condition=models.Q(('requested_asset__isnull', False)), fields=('request', 'requested_asset'), name='equipment_request_preferred_asset_unique'),
        ),
    ]
