# Generated by Django 6.1.1 on 2026-09-18 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmentrequestline_requested_asset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequestDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('request_number', models.CharField(db_index=True, max_length=24)),
                ('requester_label', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWING', 'Under review'), ('APPROVED', 'Approved'), ('READY', 'Ready'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.JSONField(default=dict)),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_equipment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-deleted_at', '-id'),
            },
        ),
    ]
