# Generated by Django 6.0.6 on 2026-06-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PICKED', 'Picked'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
