# Generated by Hermes on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventoryitem_document_inventoryitem_document_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivingticket",
            name="vendor",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
