# Generated by Django 6.0.6 on 2026-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_receivingticket_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='shipper',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='receivingline',
            name='shipper',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
