# Generated by Django 6.0.6 on 2026-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_shipper_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('OFCI', 'OFCI'), ('CFCI', 'CFCI'), ('Consumables', 'Consumables'), ('Tools', 'Tools'), ('Safety', 'Safety'), ('Misc', 'Misc')], max_length=120),
        ),
    ]
