# Generated by Django 6.0.6 on 2026-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='rack',
            field=models.CharField(blank=True, choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4'), ('R5', 'R5'), ('R6', 'R6'), ('R7', 'R7')], max_length=2),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='section',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='bin_location',
            field=models.CharField(blank=True, choices=[('1L', '1L'), ('1R', '1R'), ('2L', '2L'), ('2R', '2R'), ('3L', '3L'), ('3R', '3R'), ('Quarantine', 'Quarantine'), ('RMA', 'RMA'), ('Reels', 'Reels')], default='', help_text='Rack bin or standalone location', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_number',
            field=models.CharField(max_length=80),
        ),
    ]
