# Generated by Django 6.0.6 on 2026-06-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_rack_inventoryitem_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
    ]
