# Generated by Django 6.0.6 on 2026-06-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'name'], 'permissions': [('import_inventory', 'Can import inventory spreadsheets'), ('export_inventory', 'Can export inventory spreadsheets'), ('bulk_adjust_inventory', 'Can bulk adjust inventory'), ('clear_inventory', 'Can clear all inventory'), ('manage_storage_locations', 'Can manage storage locations'), ('view_qr_codes', 'Can view QR Codes page'), ('print_qr_codes', 'Can print QR Codes'), ('view_app_qr_code', 'Can view app login QR code'), ('scan_codes', 'Can scan barcodes and QR codes'), ('manage_users', 'Can manage warehouse users'), ('manage_groups', 'Can create and delete warehouse groups'), ('manage_group_permissions', 'Can edit warehouse group permissions')]},
        ),
        migrations.AlterModelOptions(
            name='pickticket',
            options={'ordering': ['-created_at'], 'permissions': [('print_pickticket', 'Can print material issue tickets')]},
        ),
        migrations.AlterModelOptions(
            name='receivingticket',
            options={'ordering': ['-created_at'], 'permissions': [('receive_stock', 'Can receive stock'), ('view_receiving_log', 'Can view receiving log'), ('print_receivingticket', 'Can print receiving tickets')]},
        ),
    ]
