# Generated by Django 6.0.6 on 2026-08-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryitem_options_alter_pickticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='bin_location',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='', help_text='Numeric rack bin from 1 to 6', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='rack',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='section',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=2),
        ),
    ]
