# Generated by Django 6.0.6 on 2026-09-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryitem_bin_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('requestor_name', models.CharField(max_length=120)),
                ('building_room', models.CharField(max_length=120, verbose_name='BLDG/Room #')),
                ('location', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
                ('pick_ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='material_request', to='inventory.pickticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('access_material_request_portal', 'Can access the material request portal')],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_event', to='inventory.materialrequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('material_request', 'item'), name='unique_item_per_material_request'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_request_quantity_positive')],
            },
        ),
    ]
