# Generated by Django 6.0.6 on 2026-09-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0014_materialrequest_materialrequestevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=64, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_role', to='auth.group')),
            ],
        ),
    ]
