# Generated by Django 6.0.6 on 2026-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_managedgrouprole'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='model_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='Model #'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, choices=[('OFCI', 'OFCI'), ('CFCI', 'CFCI'), ('Consumables', 'Consumables'), ('Tools', 'Tools'), ('Safety', 'Safety'), ('Equipment', 'Equipment'), ('Supplies', 'Supplies'), ('Misc', 'Misc')], max_length=120),
        ),
    ]
