# Generated by Django 6.0.6 on 2026-09-12 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryitem_model_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery date/time'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='building_room',
            field=models.CharField(blank=True, max_length=120, verbose_name='BLDG/Room #'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='requestor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('delivery_at__isnull', False)), fields=('delivery_at',), name='unique_material_request_delivery_slot'),
        ),
    ]
