# Generated by Django 6.0.6 on 2026-09-12 01:35

from django.db import migrations, models


def normalize_location_segments(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    db_alias = schema_editor.connection.alias
    items = []
    for item in InventoryItem.objects.using(db_alias).all().only("id", "section", "bin_location"):
        new_section = item.section.zfill(2) if item.section and item.section.isdigit() else item.section
        new_bin = item.bin_location.zfill(2) if item.bin_location and item.bin_location.isdigit() else item.bin_location
        if new_section != item.section or new_bin != item.bin_location:
            item.section = new_section
            item.bin_location = new_bin
            items.append(item)
    if items:
        InventoryItem.objects.using(db_alias).bulk_update(items, ["section", "bin_location"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_materialrequest_delivery_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='bin_location',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')], default='', help_text='Numeric rack bin from 1 to 6', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='section',
            field=models.CharField(blank=True, choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=2),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='delivery_at',
            field=models.DateTimeField(null=True, verbose_name='Delivery date/time'),
        ),
        migrations.RunPython(normalize_location_segments, migrations.RunPython.noop),
    ]
