# Generated by Django 6.0.6 on 2026-09-12 02:50

from django.db import migrations, models


def grant_item_barcode_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.filter(app_label='inventory', model='inventoryitem').first()
    if content_type:
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename='manage_item_barcodes',
            defaults={'name': 'Can generate item barcodes and assign UPCs'},
        )
        for group in Group.objects.filter(name__in=['Procurement Specialist', 'Logistics Manager']):
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_materialrequest_archived_at_status_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'name'], 'permissions': [('import_inventory', 'Can import inventory spreadsheets'), ('export_inventory', 'Can export inventory spreadsheets'), ('bulk_adjust_inventory', 'Can bulk adjust inventory'), ('clear_inventory', 'Can clear all inventory'), ('manage_storage_locations', 'Can manage storage locations'), ('view_qr_codes', 'Can view QR Codes page'), ('print_qr_codes', 'Can print QR Codes'), ('view_app_qr_code', 'Can view app login QR code'), ('scan_codes', 'Can scan barcodes and QR codes'), ('manage_item_barcodes', 'Can generate item barcodes and assign UPCs'), ('manage_users', 'Can manage warehouse users'), ('manage_groups', 'Can create and delete warehouse groups'), ('manage_group_permissions', 'Can edit warehouse group permissions')]},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='fb_part_number',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='FB Part #'),
        ),
        migrations.RunPython(grant_item_barcode_permission, migrations.RunPython.noop),
    ]
