# Generated by Django 6.0.6 on 2026-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_pushsubscription_pushdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
