# Generated by Django 6.0.6 on 2026-09-12 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_pushsubscription_last_success_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('retry', 'Retry scheduled'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Subscription expired')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pushdelivery',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='inventory.pushsubscription'),
        ),
    ]
