# Generated by Django 6.0.6 on 2026-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_pushdelivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
