# Generated by Django 6.0.6 on 2026-09-12 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_pushsubscription_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_acceptance_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_acceptance_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_material_request_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_request_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('delivery_acceptance_confirmed', 'Delivery acceptance confirmed')], default='created', max_length=40),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='new_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='old_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='materialrequestevent',
            name='material_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.materialrequest'),
        ),
    ]
