# Generated by Django 6.0.6 on 2026-09-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_materialrequest_delivery_acceptance_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='audience',
            field=models.CharField(choices=[('wms', 'Warehouse'), ('request_portal', 'Request portal')], default='wms', max_length=20),
        ),
    ]
