# Generated by Django 6.0.6 on 2026-09-12 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_backfill_ready_for_delivery_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_acceptance_confirmed_at__isnull', True), ('delivery_acceptance_confirmed_by__isnull', True)), models.Q(('delivery_acceptance_confirmed_at__isnull', False), ('delivery_acceptance_confirmed_by__isnull', False)), _connector='OR'), name='material_request_acceptance_fields_paired'),
        ),
        migrations.AddConstraint(
            model_name='materialrequestevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'created')), fields=('material_request',), name='unique_created_event_per_material_request'),
        ),
    ]
