# Generated by Django 6.0.6 on 2026-09-12 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_materialrequest_material_request_acceptance_fields_paired_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_not_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_not_ready_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declined_material_request_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_response_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='materialrequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('delivery_acceptance_confirmed', 'Delivery acceptance confirmed'), ('delivery_not_ready', 'Delivery not ready')], default='created', max_length=40),
        ),
    ]
