# Generated by Django 6.0.6 on 2026-09-12 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_materialrequest_delivery_not_ready_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_not_ready_at__isnull', True), ('delivery_not_ready_by__isnull', True)), models.Q(('delivery_not_ready_at__isnull', False), ('delivery_not_ready_by__isnull', False)), _connector='OR'), name='material_request_not_ready_fields_paired'),
        ),
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_acceptance_confirmed_at__isnull', True), ('delivery_not_ready_at__isnull', True), _connector='OR'), name='material_request_delivery_response_exclusive'),
        ),
    ]
