# Generated by Django 6.0.6 on 2026-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_materialrequest_material_request_not_ready_fields_paired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequestevent',
            name='change_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='materialrequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('delivery_acceptance_confirmed', 'Delivery acceptance confirmed'), ('delivery_not_ready', 'Delivery not ready')], default='created', max_length=40),
        ),
    ]
