# Generated by Django 6.0.6 on 2026-09-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_materialrequestevent_change_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequestevent',
            name='request_number_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='requestor_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='materialrequestevent',
            name='ticket_number_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='materialrequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status changed'), ('delivery_acceptance_confirmed', 'Delivery acceptance confirmed'), ('delivery_not_ready', 'Delivery not ready')], default='created', max_length=40),
        ),
        migrations.AlterField(
            model_name='materialrequestevent',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inventory.materialrequest'),
        ),
    ]
