# Generated by Django 6.0.6 on 2026-09-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_materialrequestevent_request_number_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='requestor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
