# Generated by Django 6.0.6 on 2026-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_materialrequest_requestor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
