# Generated by Django 6.0.6 on 2026-09-12 19:38

from django.db import migrations


WAREHOUSE_GROUPS = {"Procurement Specialist", "Logistics Manager"}
WAREHOUSE_CAPABILITIES = {
    "add_inventoryitem",
    "change_pickticket",
    "receive_stock",
    "manage_users",
}


def grant_existing_warehouse_roles(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    content_type, _ = ContentType.objects.get_or_create(
        app_label="inventory", model="materialrequest"
    )
    global_permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="view_all_materialrequests",
        defaults={"name": "Can view and manage all material requests"},
    )
    warehouse_groups = Group.objects.filter(
        name__in=WAREHOUSE_GROUPS,
        permissions__content_type__app_label="inventory",
        permissions__codename="view_materialrequest",
    ).filter(
        permissions__content_type__app_label="inventory",
        permissions__codename__in=WAREHOUSE_CAPABILITIES,
    ).distinct()
    for group in warehouse_groups:
        group.permissions.add(global_permission)


def remove_global_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="inventory",
        content_type__model="materialrequest",
        codename="view_all_materialrequests",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_materialrequest_urgent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("access_material_request_portal", "Can access the material request portal"),
                    ("view_all_materialrequests", "Can view and manage all material requests"),
                ],
            },
        ),
        migrations.RunPython(grant_existing_warehouse_roles, remove_global_permission),
    ]
