# Generated by Django 6.0.6 on 2026-09-12 20:48

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


def correlate_existing_receipts(apps, schema_editor):
    ReceivingLine = apps.get_model("inventory", "ReceivingLine")
    ReceivingTicket = apps.get_model("inventory", "ReceivingTicket")
    InventoryTransaction = apps.get_model("inventory", "InventoryTransaction")

    for line in ReceivingLine.objects.order_by("created_at", "pk").iterator():
        reference = uuid.uuid4()
        ticket = ReceivingTicket.objects.only("ticket_number", "created_by_id").get(
            pk=line.ticket_id
        )
        note_marker = f"Received on {ticket.ticket_number}"
        candidates = list(InventoryTransaction.objects.filter(
            Q(notes=note_marker) | Q(notes__startswith=f"{note_marker}:"),
            receiving_line__isnull=True,
            item_id=line.item_id,
            transaction_type="RECEIPT",
            quantity_delta=line.quantity,
            created_by_id=ticket.created_by_id,
        ).order_by("created_at", "pk")[:2])
        if len(candidates) != 1:
            raise RuntimeError(
                "Migration 0036 could not safely correlate receiving line "
                f"{line.pk} with exactly one immutable receipt transaction. "
                "Reconcile this line before retrying the migration."
            )
        receipt = candidates[0]
        ReceivingLine.objects.filter(pk=line.pk).update(ledger_reference=reference)
        InventoryTransaction.objects.filter(pk=receipt.pk).update(
            receiving_line_id=line.pk,
            receiving_reference=reference,
        )


def remove_receipt_correlations(apps, schema_editor):
    ReceivingLine = apps.get_model("inventory", "ReceivingLine")
    InventoryTransaction = apps.get_model("inventory", "InventoryTransaction")
    InventoryTransaction.objects.update(
        receiving_line_id=None,
        receiving_reference=None,
        reverses_transaction_id=None,
    )
    ReceivingLine.objects.update(ledger_reference=None)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_material_request_global_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventorytransaction",
            options={"base_manager_name": "objects", "ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="receivingline",
            options={"base_manager_name": "objects", "ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="receivingticket",
            options={
                "base_manager_name": "objects",
                "ordering": ["-created_at"],
                "permissions": [
                    ("receive_stock", "Can receive stock"),
                    ("view_receiving_log", "Can view receiving log"),
                    ("print_receivingticket", "Can print receiving tickets"),
                ],
            },
        ),
        migrations.AddField(
            model_name="receivingline",
            name="ledger_reference",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="receiving_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_transaction",
                to="inventory.receivingline",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="receiving_reference",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="reverses_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_transaction",
                to="inventory.inventorytransaction",
            ),
        ),
        migrations.RunPython(correlate_existing_receipts, remove_receipt_correlations),
        migrations.AlterField(
            model_name="receivingline",
            name="ledger_reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("PICK", "Pick ticket"),
                    ("RECEIPT", "Stock received"),
                    ("REVERSAL", "Receipt reversal"),
                    ("ADJUSTMENT", "Manual adjustment"),
                    ("IMPORT", "Initial import"),
                ],
                max_length=20,
            ),
        ),
    ]
