# Generated by Django 6.0.6 on 2026-09-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_materialrequest_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdocument',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type captured at upload time', max_length=64),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type captured at upload time', max_length=64),
        ),
    ]
