# Generated by Django 6.1.1 on 2026-09-13 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_itemdocument_content_type_itemimage_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'name'], 'permissions': [('import_inventory', 'Can import inventory spreadsheets'), ('export_inventory', 'Can export inventory spreadsheets'), ('bulk_adjust_inventory', 'Can bulk adjust inventory'), ('clear_inventory', 'Can clear all inventory'), ('manage_storage_locations', 'Can manage storage locations'), ('view_qr_codes', 'Can view QR Codes page'), ('print_qr_codes', 'Can print QR Codes'), ('view_app_qr_code', 'Can view app login QR code'), ('scan_codes', 'Can scan barcodes and QR codes'), ('manage_item_barcodes', 'Can generate item barcodes and assign UPCs'), ('manage_users', 'Can manage warehouse users'), ('manage_groups', 'Can create and delete warehouse groups'), ('manage_group_permissions', 'Can edit warehouse group permissions'), ('perform_cycle_count', 'Can perform cycle counts'), ('manage_cycle_counts', 'Can create and manage cycle counts')]},
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_counts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('perform_cycle_count', 'Can perform cycle counts'), ('manage_cycle_counts', 'Can create and manage cycle counts')],
            },
        ),
        migrations.CreateModel(
            name='CycleCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('system_quantity', models.IntegerField()),
                ('counted_quantity', models.IntegerField(blank=True, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_count_entries_counted', to=settings.AUTH_USER_MODEL)),
                ('cycle_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.cyclecount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_count_entries', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['category', 'item__name'],
                'indexes': [models.Index(fields=['cycle_count', 'category'], name='inventory_c_cycle_c_d63514_idx')],
            },
        ),
    ]
