# Generated by Django 6.1.1 on 2026-09-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_alter_inventoryitem_options_cyclecount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyclecount',
            options={'ordering': ['-created_at']},
        ),
    ]
