# Generated by Django 6.1.1 on 2026-09-13 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_cyclecount_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['category', 'name'], 'permissions': [('import_inventory', 'Can import inventory spreadsheets'), ('export_inventory', 'Can export inventory spreadsheets'), ('bulk_adjust_inventory', 'Can bulk adjust inventory'), ('clear_inventory', 'Can clear all inventory'), ('manage_storage_locations', 'Can manage storage locations'), ('view_qr_codes', 'Can view QR Codes page'), ('print_qr_codes', 'Can print QR Codes'), ('view_app_qr_code', 'Can view app login QR code'), ('scan_codes', 'Can scan barcodes and QR codes'), ('manage_item_barcodes', 'Can generate item barcodes and assign UPCs'), ('manage_users', 'Can manage warehouse users'), ('manage_groups', 'Can create and delete warehouse groups'), ('manage_group_permissions', 'Can edit warehouse group permissions'), ('perform_cycle_count', 'Can perform cycle counts'), ('manage_cycle_counts', 'Can create and manage cycle counts'), ('archive_cycle_counts', 'Can archive completed cycle counts')]},
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cyclecount',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts_archived', to=settings.AUTH_USER_MODEL),
        ),
    ]
