# Generated by Django 6.1.1 on 2026-09-14 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_logistics_specialist_cycle_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inventory_item', 'Inventory Item'), ('pick_ticket', 'Pick Ticket'), ('material_request', 'Material Request'), ('receiving_ticket', 'Receiving Ticket')], max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at', '-pk'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='inventory_r_user_id_7bc2a2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'object_id'), name='unique_recent_work_per_user_object')],
            },
        ),
    ]
