# Generated by Django 6.1.1 on 2026-09-14 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


MANAGER_GROUPS = ("Logistics Manager", "Sr. Logistics Manager", "Procurement Manager")


def grant_reviewer_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="inventory", model="portalaccessrequest"
    )
    permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename="review_portalaccessrequest",
        defaults={"name": "Can review portal access requests"},
    )
    for name in MANAGER_GROUPS:
        group, _ = Group.objects.get_or_create(name=name)
        group.permissions.add(permission)


def revoke_reviewer_permission(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    permission = Permission.objects.filter(
        content_type__app_label="inventory", codename="review_portalaccessrequest"
    ).first()
    if permission:
        for group in Group.objects.filter(name__in=MANAGER_GROUPS):
            group.permissions.remove(permission)


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0045_recentwork"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAccessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=150)),
                ("position", models.CharField(max_length=150)),
                ("contact_number", models.CharField(max_length=40)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("project_jobsite", models.CharField(blank=True, max_length=200)),
                ("sponsor", models.CharField(blank=True, max_length=150)),
                ("business_reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("unverified", "Awaiting email verification"), ("pending_review", "Pending manager review"), ("more_info", "More information requested"), ("approved_setup", "Approved; awaiting password setup"), ("active", "Active"), ("denied", "Denied"), ("expired", "Expired")], db_index=True, default="unverified", max_length=24)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("access_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_portal_access_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="portal_access_request", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("review_portalaccessrequest", "Can review portal access requests")],
            },
        ),
        migrations.CreateModel(
            name="PortalAccessAuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(db_index=True, max_length=48)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="inventory.portalaccessrequest")),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
        migrations.CreateModel(
            name="PortalAccessThrottle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=32)),
                ("key_digest", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={"constraints": [models.UniqueConstraint(fields=("action", "key_digest"), name="unique_portal_throttle_key")]},
        ),
        migrations.CreateModel(
            name="PortalAccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("verify_email", "Verify email"), ("more_info", "Provide more information"), ("set_password", "Set password")], max_length=20)),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tokens", to="inventory.portalaccessrequest")),
            ],
            options={"indexes": [models.Index(fields=["purpose", "digest"], name="inventory_p_purpose_e2432a_idx")]},
        ),
        migrations.RunPython(grant_reviewer_permission, revoke_reviewer_permission),
    ]
