# Generated by Django 6.1.1 on 2026-09-14 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_existing_allocations(apps, schema_editor):
    MaterialRequestLine = apps.get_model('inventory', 'MaterialRequestLine')
    MaterialRequestLine.objects.update(allocated_quantity=models.F('quantity'))


def reset_existing_allocations(apps, schema_editor):
    MaterialRequestLine = apps.get_model('inventory', 'MaterialRequestLine')
    MaterialRequestLine.objects.update(allocated_quantity=0)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_portal_access_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackorderFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialBackorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backorder_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially fulfilled'), ('READY', 'Ready to fulfill'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'permissions': [('manage_backorders', 'Can manage and fulfill material backorders')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under review'), ('ORDERED', 'Ordered'), ('PARTIAL', 'Partially received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('po_number', models.CharField(blank=True, max_length=80)),
                ('ordered_quantity', models.PositiveIntegerField(default=0)),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('expected_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'permissions': [('manage_procurement_requisitions', 'Can manage procurement requisitions')],
            },
        ),
        migrations.AddField(
            model_name='materialrequestline',
            name='allocated_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_existing_allocations, reset_existing_allocations),
        migrations.AddField(
            model_name='materialrequestline',
            name='shortage_action',
            field=models.CharField(blank=True, choices=[('available_only', 'Fulfill available quantity only'), ('backorder', 'Backorder the remaining quantity'), ('procurement', 'Send the remaining quantity to Procurement')], default='', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='materialrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__lte', models.F('quantity'))), name='material_request_allocation_not_over_requested'),
        ),
        migrations.AddField(
            model_name='backorderfulfillment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backorderfulfillment',
            name='pick_ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='backorder_fulfillment', to='inventory.pickticket'),
        ),
        migrations.AddField(
            model_name='materialbackorder',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backorder', to='inventory.materialrequestline'),
        ),
        migrations.AddField(
            model_name='backorderfulfillment',
            name='backorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='inventory.materialbackorder'),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='backorder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requisition', to='inventory.materialbackorder'),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementrequisition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_procurement_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='materialbackorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='backorder_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='materialbackorder',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_quantity__lte', models.F('quantity'))), name='backorder_fulfilled_not_over_quantity'),
        ),
        migrations.AddConstraint(
            model_name='procurementrequisition',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('ordered_quantity'))), name='procurement_received_not_over_ordered'),
        ),
    ]
