# Generated by Django 6.1.1 on 2026-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_backorderfulfillment_materialbackorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequestline',
            name='shortage_action',
            field=models.CharField(blank=True, choices=[('available_only', 'Use available stock and cancel the rest'), ('backorder', 'Request the rest when available'), ('procurement', 'Ask Procurement to purchase the rest')], default='', max_length=24),
        ),
    ]
