# Generated by Django 6.1.1 on 2026-09-15 20:05

from django.db import migrations


MANAGER_GROUPS = (
    "Logistics Manager",
    "Sr. Logistics Manager",
    "Procurement Manager",
)

# Verified pre-0049 production grants are intentionally preserved on rollback.
PERMISSIONS_ADDED_BY_GROUP = {
    "Logistics Manager": {
        "delete_materialrequest",
        "delete_materialrequestline",
        "delete_materialbackorder",
        "delete_procurementrequisition",
        "delete_backorderfulfillment",
    },
    "Sr. Logistics Manager": {
        "delete_materialbackorder",
        "delete_procurementrequisition",
        "delete_backorderfulfillment",
    },
    "Procurement Manager": {
        "delete_materialbackorder",
        "delete_procurementrequisition",
        "delete_backorderfulfillment",
    },
}

DELETE_PERMISSIONS = (
    ("materialrequest", "delete_materialrequest", "Can delete material request"),
    ("materialrequestline", "delete_materialrequestline", "Can delete material request line"),
    ("pickticket", "delete_pickticket", "Can delete pick ticket"),
    ("pickticketline", "delete_pickticketline", "Can delete pick ticket line"),
    ("materialbackorder", "delete_materialbackorder", "Can delete material backorder"),
    (
        "procurementrequisition",
        "delete_procurementrequisition",
        "Can delete procurement requisition",
    ),
    (
        "backorderfulfillment",
        "delete_backorderfulfillment",
        "Can delete backorder fulfillment",
    ),
)


def grant_manager_cascade_permissions(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    permissions = []
    for model, codename, name in DELETE_PERMISSIONS:
        content_type, _ = ContentType.objects.get_or_create(
            app_label="inventory",
            model=model,
        )
        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)
    for group_name in MANAGER_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(*permissions)


def revoke_manager_cascade_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    for group_name, added_codenames in PERMISSIONS_ADDED_BY_GROUP.items():
        group = Group.objects.filter(name=group_name).first()
        if group is None:
            continue
        permissions = Permission.objects.filter(
            content_type__app_label="inventory",
            codename__in=added_codenames,
        )
        group.permissions.remove(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0048_alter_materialrequestline_shortage_action"),
    ]

    operations = [
        migrations.RunPython(
            grant_manager_cascade_permissions,
            revoke_manager_cascade_permissions,
        ),
    ]
