# Generated by Django 6.1.1 on 2026-09-17 16:39

from collections import defaultdict, deque

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_completed_pick_quantities(apps, schema_editor):
    PickTicketLine = apps.get_model('inventory', 'PickTicketLine')
    PickTicket = apps.get_model('inventory', 'PickTicket')
    MaterialRequest = apps.get_model('inventory', 'MaterialRequest')
    InventoryTransaction = apps.get_model('inventory', 'InventoryTransaction')
    PickTicketLine.objects.exclude(ticket__status='OPEN').update(
        picked_quantity=models.F('quantity')
    )
    reservation_transactions = defaultdict(deque)
    for transaction in InventoryTransaction.objects.filter(
        transaction_type='PICK', pick_ticket_id__isnull=False
    ).order_by('created_at', 'pk').values(
        'pk', 'pick_ticket_id', 'item_id', 'notes'
    ).iterator():
        reservation_transactions[
            (
                transaction['pick_ticket_id'],
                transaction['item_id'],
                transaction['notes'],
            )
        ].append(transaction['pk'])
    for line in PickTicketLine.objects.select_related('ticket').order_by(
        'ticket_id', 'item_id', 'created_at', 'pk'
    ).iterator():
        candidates = reservation_transactions[
            (
                line.ticket_id,
                line.item_id,
                f"Picked on {line.ticket.ticket_number}",
            )
        ]
        if candidates:
            PickTicketLine.objects.filter(pk=line.pk).update(
                reservation_transaction_id=candidates.popleft()
            )

    linked_assignments = {
        pick_ticket_id: (assigned_to_id, updated_at)
        for pick_ticket_id, assigned_to_id, updated_at in MaterialRequest.objects.filter(
            pick_ticket_id__isnull=False,
            assigned_to_id__isnull=False,
        ).values_list('pick_ticket_id', 'assigned_to_id', 'updated_at')
    }
    assigned_tickets = list(
        PickTicket.objects.filter(
            pk__in=linked_assignments,
            status='OPEN',
            assigned_to_id__isnull=True,
        )
    )
    for ticket in assigned_tickets:
        ticket.assigned_to_id, ticket.assigned_at = linked_assignments[ticket.pk]
    if assigned_tickets:
        PickTicket.objects.bulk_update(
            assigned_tickets, ['assigned_to', 'assigned_at']
        )


def clear_backfilled_pick_quantities(apps, schema_editor):
    PickTicketLine = apps.get_model('inventory', 'PickTicketLine')
    InventoryItem = apps.get_model('inventory', 'InventoryItem')
    InventoryTransaction = apps.get_model('inventory', 'InventoryTransaction')
    for line in PickTicketLine.objects.exclude(picked_quantity=None).iterator():
        stock_delta = line.picked_quantity - line.quantity
        if stock_delta:
            InventoryItem.objects.filter(pk=line.item_id).update(
                quantity_on_hand=models.F('quantity_on_hand') + stock_delta
            )
        if line.pick_variance_transaction_id:
            InventoryTransaction.objects.filter(
                pk=line.pick_variance_transaction_id
            ).delete()
    PickTicketLine.objects.update(
        picked_quantity=None,
        pick_variance_reason='',
        pick_variance_transaction=None,
        reservation_transaction=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_manager_material_request_cascade_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickticket',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_pick_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pick_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='picked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='qa_checked_by_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pickticket',
            name='qa_checked_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_checked_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickticketline',
            name='pick_variance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickticketline',
            name='pick_variance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_variance_line', to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='pickticketline',
            name='picked_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickticketline',
            name='reservation_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_pick_line', to='inventory.inventorytransaction'),
        ),
        migrations.RunPython(
            backfill_completed_pick_quantities,
            clear_backfilled_pick_quantities,
        ),
        migrations.AddConstraint(
            model_name='pickticketline',
            constraint=models.CheckConstraint(condition=models.Q(('picked_quantity__isnull', True), ('picked_quantity', models.F('quantity')), models.Q(('pick_variance_reason', ''), _negated=True), _connector='OR'), name='pick_variance_requires_reason'),
        ),
    ]
