# Generated by Django 6.1.1 on 2026-09-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_backfill_locked_ticket_pickers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='fb_part_number',
        ),
    ]
