"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from csp.constants import NONCE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-p*p6qa7xo(+%whg@@(cxcl)58%ynvi&+=j@xcm($f7e&3ux_+4",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() in {"1", "true", "yes", "on"}

# ALLOWED_HOSTS governs which Host: headers Django will accept requests for.
# Internal LAN/Tailscale hostnames were pruned on 2026-09-13 to reduce attack
# surface; if you need to expose the app directly on the internal network
# again, add them back as concrete entries (no wildcards) and document why.
# The reverse proxy at bbx.rplwms.com / requests.rplwms.com terminates TLS
# and forwards to gunicorn on 127.0.0.1:8089, so this list only needs
# loopback entries plus the public hostnames.
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'bbx.rplwms.com',
    'requests.rplwms.com',
    'rplwms.com',
    'www.rplwms.com',
    'wms.bonksystems.com',
    'warehouse.bonksystems.com',
]

APP_URL = 'https://bbx.rplwms.com'
REQUESTS_URL = 'https://requests.rplwms.com'

WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get("WEBPUSH_VAPID_PUBLIC_KEY", "")
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get("WEBPUSH_VAPID_PRIVATE_KEY", "")
WEBPUSH_VAPID_SUBJECT = os.environ.get("WEBPUSH_VAPID_SUBJECT", "mailto:admin@rplwms.com")

# Ready-for-delivery email. Production can point these at an authenticated
# relay; localhost is safe for the existing Postfix installation.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "127.0.0.1")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").lower() == "true"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Black Box RPL Warehouse <noreply@rplwms.com>")
REQUEST_PORTAL_BASE_URL = os.getenv(
    "REQUEST_PORTAL_BASE_URL", "https://requests.rplwms.com"
)

CSRF_TRUSTED_ORIGINS = [
    'https://bbx.rplwms.com',
    'https://requests.rplwms.com',
    'https://rplwms.com',
    'https://www.rplwms.com',
    'https://wms.bonksystems.com',
    'https://warehouse.bonksystems.com',
    'https://warehouse.directline.local',
]
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
RUNNING_TESTS = "test" in sys.argv or "pytest" in sys.modules
SECURE_SSL_REDIRECT = not RUNNING_TESTS
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'csp',
    'inventory',
]

AXES_ENABLED = not RUNNING_TESTS
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.25  # hours (15 minutes)
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']
AXES_LOCKOUT_TEMPLATE = 'inventory/registration/lockout.html'
AXES_VERBOSE_IP_AND_USERNAME = False

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'", NONCE),
        "style-src": ("'self'", "'unsafe-inline'"),
        "img-src": ("'self'", "data:"),
        "connect-src": ("'self'",),
        "font-src": ("'self'",),
        "object-src": ("'none'",),
        "base-uri": ("'self'",),
        "frame-ancestors": ("'none'",),
        "form-action": ("'self'",),
    },
}
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
if not RUNNING_TESTS:
    AUTHENTICATION_BACKENDS.insert(0, 'axes.backends.AxesStandaloneBackend')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MIDDLEWARE = [
    'csp.middleware.CSPMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'inventory.middleware.ProxySSLHeaderMiddleware',
    'inventory.middleware.HostURLConfMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Media files (user-uploaded item images, documents, receiving docs)
# https://docs.djangoproject.com/en/6.0/topics/files/
#
# NOTE: Media is served through permission-checked Django views, NOT directly
# via STATIC-style serving, to enforce access control and prevent IDOR.
# See inventory.views.serve_item_image / serve_item_document.

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Upload limits (defense-in-depth; views also enforce per-file validation)
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# Allowed image MIME types for ItemImage uploads
ITEM_IMAGE_ALLOWED_MIME_TYPES = frozenset({
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/gif",
})

# Allowed document MIME types for ItemDocument uploads
ITEM_DOCUMENT_ALLOWED_MIME_TYPES = frozenset({
    "application/pdf",
})

ITEM_IMAGE_MAX_BYTES = 10 * 1024 * 1024   # 10 MB
ITEM_DOCUMENT_MAX_BYTES = 25 * 1024 * 1024  # 25 MB
